### PR TITLE
A bit of cleanup in the AbstractSchemaTranslator class

### PR DESCRIPTION
**Pull request by elecharny**
o Used the ObjectClassRegistrylookup() directlry without passing through
the OID, because the method already does that internally
o Added some missing {} after a 'if' 
o Used the ldapAttributeType.getSyntax().isHumanReadable() methd to
check if an AT is binary, instead of using the AT's OID
o Used the bytes = ldapValue.getBytes() method to get the correct
byte[], instead of using a complex ByteArrayOutputStream conversion.
o Added <?> to all the Class uses.

### CODE REVIEW

**Comment by elecharny** [comment]
A quick question : when dealing with rogue servers like AD, are we sure the AttributeType will correctly be 'informed' that the values are binary or string through is isHumanReadable flag?

If not, my patch will not work.

**Comment by semancik** [comment]
No. We are not sure. Nothing is sure with AD :-) I do not remember how AD handles this. It has to be tested. There is custom BinaryAttributeDetector that takes care of binary vs string cases.

**Comment by elecharny** [comment]
Just in case, fixing my fix...

**Comment by semancik** [comment]
Is your fix fixed or are you still working on it? Please let me know when it is the right time to look at this and merge it.

**Comment by elecharny** [comment]
yes, my fix has been fixed :-)

**Pull request merged**
