### PR TITLE
Some cleanup/NPE removals

### PR DESCRIPTION
**Pull request by elecharny**
Just for the sake of less warnings in my IDE ;-)

### CODE REVIEW

**Comment by elecharny** [comment]
Replaced the constants from LdapConstants by constants from SchemaConstants.

**Comment by elecharny** [comment]
Some more cleanup and NPE avoidance

**Comment by elecharny** [comment]
I have to learn how to create a PR per issue :-) Too new to github, still mainly stuck in SVN ...

**Comment by elecharny** [comment]
Q : is there any mandatory Java version ? Like, Java 7 ?

**Comment by semancik** [comment]
No problem. Code improvements are important. The process of delivering them is not that important.

**Comment by semancik** [comment]
Ad Java version: this is kind of a grey zone. As far as I remember the ConnId framework is still Java 6. But that's just too old. Therefore we sacrifice some compatibility and this connector is java 7 (as all our connectors). We might consider switching to java 8 quite soon.

**Comment by elecharny** [comment]
Thanks for the answers.

I think you know that the ModifyTimestampSyncStrategy class will not be able to know about deleted entries ?

**Comment by semancik** [comment]
Sure. That's a know limitation. And that's the reason that we need better sync strategies.

**Comment by elecharny** [comment]
Working on a RFC 4533 sync atm. That is why I'm pushing some PR -)

**Comment by semancik** [comment]
Yeah. I figured that out :-) Thanks for that. Let me know if you need any assistance.

**Comment by elecharny** [comment]
So far, so good. I've built a test that allows me to use the LdapConnector in insolation. But I'm still looking at the code atm, in order to get a grip about what's it's doing.

**Comment by semancik** [comment]
Would be nice to have unit tests in the LDAP connector project. This will require standalone LDAP instance (ApacheDS?). The connector was not tested with ApacheDS yet, so this can be additional benefit.
We have quite intense tests in midPoint that also cover this connector. Tests with several different LDAP servers. That's how I make sure that the connector works. But there are no connector unit tests. Would be nice to have them.

**Comment by elecharny** [comment]
I can add some tests with ApacheDS embedded. That's probably a good starting point to get away from trivial errors, but of course that will not clear up the potential problems with the various RFCs violations of many LDAP servers...

**Comment by semancik** [comment]
Understood. But for the standard-violating servers I already have a comprehensive test suite. But it requires very specific and quite complex environment (read: it only runs in my lab). And it has quite a long runtime. I'm not worried about these broken servers. We will catch these issues eventually. What I'm worried about are trivial mistakes (NPEs and things like that). Unit tests are the best way to address these. That will speed up the development cycle. And more importantly: it will open up the connector development to more people.

**Pull request merged**
